site_name: NithronOS Documentation
site_url: https://docs.nithronos.org
site_description: Complete documentation for NithronOS - The secure, self-hosted storage and app platform
site_author: NithronOS Team
copyright: Copyright &copy; 2024 NithronOS

repo_url: https://github.com/Nithronverse/NithronOS
repo_name: NithronOS
edit_uri: edit/main/docs/

theme:
  name: material
  language: en
  
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.expand
    - navigation.path
    - navigation.prune
    - navigation.indexes
    - navigation.top
    - navigation.footer
    - toc.follow
    - toc.integrate
    - search.suggest
    - search.highlight
    - search.share
    - header.autohide
    - content.code.annotate
    - content.code.copy
    - content.code.select
    - content.tabs.link
    - content.tooltips
    
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
        
  font:
    text: Inter
    code: JetBrains Mono

plugins:
  - search:
      separator: '[\s\-\.]+'
      lang:
        - en

extra:
  version: v0.9.5-pre-alpha
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/Nithronverse/NithronOS
    - icon: fontawesome/brands/discord
      link: https://discord.gg/qzB37WS5AT
      name: Official Community Forum
    - icon: fontawesome/brands/patreon
      link: https://patreon.com/Nithron
      name: Support on Patreon

markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
      toc_depth: 3
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - pymdownx.snippets

nav:
  - Home: index.md
