version: '3.9'

services:
  n8n:
    image: n8nio/n8n:${N8N_VERSION:-latest}
    container_name: nos-app-n8n-app-1
    restart: unless-stopped
    ports:
      - "${N8N_PORT:-5678}:5678"
    volumes:
      - ./data/n8n:/home/node/.n8n
      - ./data/files:/files
    environment:
      - N8N_BASIC_AUTH_ACTIVE=${N8N_BASIC_AUTH_ACTIVE:-true}
      - N8N_BASIC_AUTH_USER=${N8N_BASIC_AUTH_USER}
      - N8N_BASIC_AUTH_PASSWORD=${N8N_BASIC_AUTH_PASSWORD}
      - N8N_HOST=${N8N_HOST:-localhost}
      - N8N_PORT=5678
      - N8N_PROTOCOL=${N8N_PROTOCOL:-http}
      - NODE_ENV=production
      - WEBHOOK_URL=${WEBHOOK_URL:-http://localhost:5678}
      - TZ=${TZ:-UTC}
      - DB_TYPE=postgresdb
      - DB_POSTGRESDB_HOST=postgres
      - DB_POSTGRESDB_PORT=5432
      - DB_POSTGRESDB_DATABASE=${DB_NAME:-n8n}
      - DB_POSTGRESDB_USER=${DB_USER:-n8n}
      - DB_POSTGRESDB_PASSWORD=${DB_PASSWORD}
      - EXECUTIONS_PROCESS=${EXECUTIONS_PROCESS:-main}
      - GENERIC_TIMEZONE=${TZ:-UTC}
      - N8N_ENCRYPTION_KEY=${N8N_ENCRYPTION_KEY}
    depends_on:
      postgres:
        condition: service_healthy
    security_opt:
      - no-new-privileges:true
    labels:
      - "nos.app.id=n8n"
      - "nos.app.name=n8n Workflow Automation"
      - "nos.app.version=${N8N_VERSION:-latest}"
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:5678/healthz"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

  postgres:
    image: postgres:${POSTGRES_VERSION:-15-alpine}
    container_name: nos-app-n8n-db-1
    restart: unless-stopped
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${DB_USER:-n8n}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME:-n8n}
      - PGDATA=/var/lib/postgresql/data/pgdata
    security_opt:
      - no-new-privileges:true
    labels:
      - "nos.app.id=n8n"
      - "nos.app.component=database"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER:-n8n}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

networks:
  default:
    name: n8n-network
