version: '3.9'

services:
  jellyfin:
    image: jellyfin/jellyfin:${JELLYFIN_VERSION:-10.8}
    container_name: nos-app-jellyfin-jellyfin-1
    restart: unless-stopped
    user: "${PUID:-1000}:${PGID:-1000}"
    ports:
      - "${JELLYFIN_PORT:-8096}:8096"
      - "${JELLYFIN_DISCOVERY_PORT:-7359}:7359/udp"
      - "${JELLYFIN_DLNA_PORT:-1900}:1900/udp"
    volumes:
      - ./data/config:/config
      - ./data/cache:/cache
      - ${MEDIA_PATH:-./data/media}:/media:ro
    environment:
      - JELLYFIN_PublishedServerUrl=${JELLYFIN_URL:-http://localhost:8096}
      - TZ=${TZ:-UTC}
    security_opt:
      - no-new-privileges:true
    labels:
      - "nos.app.id=jellyfin"
      - "nos.app.name=Jellyfin"
      - "nos.app.version=${JELLYFIN_VERSION:-10.8}"
    devices:
      # Optional: for hardware acceleration (commented out by default)
      # - /dev/dri:/dev/dri
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8096/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
