openapi: 3.0.3
info:
  title: NithronOS API
  version: 0.1.0
  description: API for nOS backend
servers:
  - url: http://127.0.0.1:9000
paths:
  /api/health:
    get:
      summary: Health check
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Health'
  /api/disks:
    get:
      summary: List disks
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  disks:
                    type: array
                    items:
                      $ref: '#/components/schemas/Disk'
                required: [disks]
  /api/pools:
    get:
      summary: List storage pools
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Pool'
  /api/shares:
    get:
      summary: List shares
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Share'
  /api/apps:
    get:
      summary: App catalog
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/App'
  /api/remote/status:
    get:
      summary: Remote access status
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RemoteStatus'
components:
  schemas:
    Health:
      type: object
      properties:
        ok:
          type: boolean
        version:
          type: string
      required: [ok, version]
    Disk:
      type: object
      properties:
        name:
          type: string
        kname:
          type: string
          nullable: true
        path:
          type: string
          nullable: true
        size:
          type: integer
          format: int64
        type:
          type: string
        rota:
          type: boolean
          nullable: true
        tran:
          type: string
          nullable: true
        vendor:
          type: string
          nullable: true
        model:
          type: string
          nullable: true
        serial:
          type: string
          nullable: true
        mountpoint:
          nullable: true
        fstype:
          type: string
          nullable: true
        smart:
          $ref: '#/components/schemas/SmartSummary'
      required: [name, size, type]
    SmartSummary:
      type: object
      properties:
        healthy:
          type: boolean
          nullable: true
        temp_c:
          type: integer
          nullable: true
        power_on_hours:
          type: integer
          nullable: true
    Pool:
      type: object
      properties:
        id:
          type: string
    Share:
      type: object
      properties:
        id:
          type: string
    App:
      type: object
      properties:
        id:
          type: string
        status:
          type: string
          enum: [installed, not_installed, updating]
      required: [id, status]
    RemoteStatus:
      type: object
      properties:
        mode:
          type: string
          enum: [lan-only, tunnel, vpn]
        https:
          type: boolean
      required: [mode, https]



