version: '3.9'

services:
  db:
    image: postgres:15-alpine
    container_name: nos-app-nextcloud-db-1
    restart: unless-stopped
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${POSTGRES_DB:-nextcloud}
      - POSTGRES_USER=${POSTGRES_USER:-nextcloud}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    security_opt:
      - no-new-privileges:true
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-nextcloud}"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: nos-app-nextcloud-redis-1
    restart: unless-stopped
    command: redis-server --requirepass ${REDIS_PASSWORD:-changeme}
    security_opt:
      - no-new-privileges:true
    read_only: true
    tmpfs:
      - /var/run/redis
    healthcheck:
      test: ["CMD", "redis-cli", "--raw", "incr", "ping"]
      interval: 10s
      timeout: 3s
      retries: 5

  app:
    image: nextcloud:${NEXTCLOUD_VERSION:-28}-apache
    container_name: nos-app-nextcloud-app-1
    restart: unless-stopped
    ports:
      - "${NEXTCLOUD_PORT:-8081}:80"
    volumes:
      - ./data/nextcloud:/var/www/html
      - ./data/apps:/var/www/html/custom_apps
      - ./data/config:/var/www/html/config
      - ./data/data:/var/www/html/data
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_DB=${POSTGRES_DB:-nextcloud}
      - POSTGRES_USER=${POSTGRES_USER:-nextcloud}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - REDIS_HOST=redis
      - REDIS_HOST_PASSWORD=${REDIS_PASSWORD:-changeme}
      - NEXTCLOUD_ADMIN_USER=${NEXTCLOUD_ADMIN_USER:-admin}
      - NEXTCLOUD_ADMIN_PASSWORD=${NEXTCLOUD_ADMIN_PASSWORD}
      - NEXTCLOUD_TRUSTED_DOMAINS=${NEXTCLOUD_TRUSTED_DOMAINS:-localhost}
      - OVERWRITEPROTOCOL=${OVERWRITE_PROTOCOL:-http}
      - OVERWRITEHOST=${OVERWRITE_HOST:-localhost:8081}
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    security_opt:
      - no-new-privileges:true
    labels:
      - "nos.app.id=nextcloud"
      - "nos.app.name=Nextcloud"
      - "nos.app.version=${NEXTCLOUD_VERSION:-28}"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/status.php"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

  cron:
    image: nextcloud:${NEXTCLOUD_VERSION:-28}-apache
    container_name: nos-app-nextcloud-cron-1
    restart: unless-stopped
    volumes:
      - ./data/nextcloud:/var/www/html
      - ./data/apps:/var/www/html/custom_apps
      - ./data/config:/var/www/html/config
      - ./data/data:/var/www/html/data
    entrypoint: /cron.sh
    depends_on:
      - db
      - redis
      - app
    security_opt:
      - no-new-privileges:true
