name: Contract

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23.x'
      - name: Install web deps
        working-directory: web
        run: npm ci
      - name: Extract FE contract
        run: node web/scripts/extract-nos-contract.mjs
      - name: Dump backend routes
        working-directory: backend/nosd
        run: go run ./cmd/route-dump > ../../route_dump.json
      - name: Verify FE-BE contract
        run: node scripts/verify-fe-be-contract.mjs
      - name: Go tests
        working-directory: backend/nosd
        run: go test ./...
