name: ISO

on:
  workflow_run:
    workflows: ["CI"]   # <-- CHANGE if your deb-building workflow has a different display name
    types: [completed]

jobs:
  build-iso:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    permissions:
      actions: read       # required to download artifacts from another workflow run
      contents: read

    steps:
      - name: Check out same commit as CI
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.workflow_run.head_sha }}

      - name: Download .deb artifacts from the CI run
        uses: dawidd6/action-download-artifact@v3
        with:
          run_id: ${{ github.event.workflow_run.id }}
          name: debs        # <-- CHANGE if your CI uploads a different artifact name
          path: dist/deb

      - name: Install ISO build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y live-build xorriso squashfs-tools cpio debootstrap genisoimage || true

      - name: Prep packages for ISO build
        run: |
          mkdir -p packaging/iso/local-debs
          cp -v dist/deb/*.deb packaging/iso/local-debs/

      - name: Build ISO
        run: |
          bash packaging/iso/build.sh packaging/iso/local-debs

      - name: Upload ISO artifact
        uses: actions/upload-artifact@v4
        with:
          name: iso
          path: dist/iso/*.iso
name: ISO

on:
  push:
    tags:
      - 'v*'

jobs:
  build-iso:
    needs: deb-packages
    runs-on: ubuntu-latest
    container:
      image: debian:bookworm
    steps:
      - name: Install deps
        run: |
          apt-get update
          apt-get install -y git live-build ca-certificates curl make build-essential debhelper devscripts fakeroot golang-go nodejs npm
      - name: Checkout
        uses: actions/checkout@v4
      - name: Download debs
        uses: actions/download-artifact@v4
        with:
          name: debs
          path: dist/deb
      - name: Prep packages for ISO
        run: |
          mkdir -p packaging/iso/local-debs
          cp -v dist/deb/*.deb packaging/iso/local-debs/
      - name: Stage debs into ISO build
        run: |
          mkdir -p packaging/iso/debian/config/includes.chroot/root/debs
          cp -v packaging/iso/local-debs/*.deb packaging/iso/debian/config/includes.chroot/root/debs/
      - name: Prepare debs
        run: |
          ls -l packaging/iso/debian/config/includes.chroot/root/debs || true
      - name: Build ISO
        working-directory: packaging/iso/debian
        run: |
          ./auto/config
          lb build
      - name: Upload ISO
        uses: actions/upload-artifact@v4
        with:
          name: nithronos-${{ github.ref_name }}-amd64.iso
          path: packaging/iso/debian/live-image-amd64.hybrid.iso
      - name: Smoke test in QEMU
        if: ${{ runner.os == 'Linux' }}
        run: |
          apt-get update && apt-get install -y qemu-system-x86 curl
          bash scripts/qemu-smoke.sh packaging/iso/debian/live-image-amd64.hybrid.iso

