name: ISO

on:
  # Build an ISO right after our main workflow finishes successfully
  workflow_run:
    workflows: ["ci.yml"]   # change to your main workflow's display name if needed
    types: [completed]
  # Allow manual runs too (optional)
  workflow_dispatch:

jobs:
  build-iso:
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name == 'workflow_dispatch' }}
    runs-on: ubuntu-latest
    permissions:
      actions: read   # needed to download artifacts from another run
      contents: read

    steps:
      - name: Checkout the same commit as the triggering run (or default branch on manual)
        uses: actions/checkout@v4
        with:
          # head_sha only exists for workflow_run; for manual it will use default branch
          ref: ${{ github.event.workflow_run.head_sha || github.sha }}

      - name: Download .deb artifacts from CI
        if: ${{ github.event_name == 'workflow_run' }}
        uses: dawidd6/action-download-artifact@v3
        with:
          run_id: ${{ github.event.workflow_run.id }}
          name: debs              # <-- CHANGE if your CI uploads a different artifact name
          path: dist/deb

      - name: Ensure ISO build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y live-build xorriso squashfs-tools cpio debootstrap genisoimage

      - name: Prepare packages for ISO build
        run: |
          mkdir -p packaging/iso/local-debs dist/iso
          # If no artifacts (manual run), keep going but warn
          if ls dist/deb/*.deb 1>/dev/null 2>&1; then
            cp -v dist/deb/*.deb packaging/iso/local-debs/
          else
            echo "::warning::No .deb artifacts found in dist/deb; ensure your main CI uploads 'debs' artifact."
          fi

      - name: Build ISO
        run: |
          bash packaging/iso/build.sh packaging/iso/local-debs

      - name: Upload ISO artifact
        uses: actions/upload-artifact@v4
        with:
          name: iso
          path: dist/iso/*.iso

