name: (deprecated) Lint and Typecheck

on:
  workflow_dispatch:

jobs:
  note:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Lint is consolidated into CI workflow. This job is a placeholder."


