name: Validate Caddyfile

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  caddy-validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Caddy
        run: |
          set -euxo pipefail
          sudo apt-get update
          sudo apt-get install -y debian-keyring debian-archive-keyring apt-transport-https curl gnupg
          curl -1sLf 'https://dl.cloudsmith.io/public/caddy/stable/gpg.key' | sudo gpg --dearmor -o /usr/share/keyrings/caddy-stable-archive-keyring.gpg
          curl -1sLf 'https://dl.cloudsmith.io/public/caddy/stable/debian.deb.txt' | sudo tee /etc/apt/sources.list.d/caddy-stable.list
          sudo apt-get update
          sudo apt-get install -y caddy

      - name: Validate Caddyfile
        run: |
          which caddy || true
          caddy validate --config packaging/iso/debian/config/includes.chroot/etc/caddy/Caddyfile
          ss -lnt || true


